---
sudo: required
services:
    - docker
language: generic
install:
    - pip install --user covimerage==0.2.0 mwclient==0.10.0 flake8==3.7.8
script: |
    ./run_tests.sh --profile
after_success: |
    set -eo pipefail
    for vim in vim neovim; do
        profile_file=$(ls | grep "profile_file_${vim}" | sort | tail -n 1)
        sed -i "s,/testplugin/,$PWD/,g" "$profile_file"
        python -m covimerage write_coverage --source "$(pwd)" --append "${profile_file}"
    done
    python -m covimerage -vv xml
    python -m covimerage report -m
    bash <(curl -s https://codecov.io/bash) -X search -X gcov -X coveragepy -f coverage.xml
