---
sudo: required
services:
    - docker
language: python
python:
    - "3.7"

install:
    - pip install codecov==2.0.15 covimerage==0.2.1 mwclient==0.10.0 flake8==3.7.8 coverage==4.5.4

script:
    # Run Python tests
    - python -m coverage run -m unittest discover test
    - coverage xml -o coverage_python.xml

    # Run vimscript tests
    - ./run_tests.sh --profile

after_success: |
    set -eo pipefail
    for vim in vim neovim; do
        profile_file=$(ls | grep "profile_file_${vim}" | sort | tail -n 1)
        sed -i "s,/testplugin/,$PWD/,g" "$profile_file"
        python -m covimerage write_coverage --source "$(pwd)" --append "${profile_file}"
    done
    python -m covimerage -vv xml
    python -m covimerage report -m
    bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
